### ISSUE TITLE
AlwaysArray parsing option

### ISSUE THREAD

**Issue by shawnmitchell** [jhuckaby/pixl-xml#15]
The `alwaysArray()` utility function is nice, but how about a parsing option to always wrap single elements in an array?

**Comment by 73rhodes** [comment]
+1 This would be very useful.

**Comment by jhuckaby** [comment]
You got it.  Added in v1.0.13.

### forceArrays

By default single elements are not represented as arrays, until another element with the same appears at the same level in the XML tree.  However, if you want to force every element into an array all the time, even when there is only a single element with a given name, set the `forceArrays` property to true.  Example:

```js
var xml_string = '<?xml version="1.0"?><Document>' + 
	'<Simple>Hello</Simple>' + 
	'<Node Key="Value">Complex</Node>' + 
	'</Document>';

var doc = XML.parse( xml_string, { forceArrays: true } );
console.log( doc );
```

With the `forceArrays` flag set to true, this would produce the following object:

```js
{
	"Simple": [
		"Hello"
	],
	"Node": [
		{
			"Key": "Value",
			"_Data": "Complex"
		}
	]
}
```

Please note that this feature applies only to elements, not attributes.
