### ISSUE TITLE
Provide Typescript definitions

### ISSUE THREAD

**Issue by bhagyas** [jhuckaby/pixl-xml#19]
^

**Comment by evanshortiss** [comment]
I will make a PR for this shortly. I have some definitions in a repository I'm working on.

**Comment by evanshortiss** [comment]
PR made, but closed in favour of adding types to DefinitelyTyped.

**Comment by Arelav** [comment]
@evanshortiss I can't find for some reason any type definitions for this library. How can I install it from npm?
Thanks.

**Comment by evanshortiss** [comment]
@Arelav PR now open with DefinitelyTyped - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37683/files

Once that's merged do `npm i @types/pixl-xml`

**Comment by Arelav** [comment]
@evanshortiss Thanks. That's what I tried to do and didn't find something because it's pending to be merged.

**Comment by evanshortiss** [comment]
@Arelav should be working now, or soon since they just merged it.

**Comment by evanshortiss** [comment]
@jhuckaby you can close this now since `npm i @types/pixl-xml` is available.

**Comment by jhuckaby** [comment]
Got it.  I still have no idea what any of this means (TypeScript n00b here), but I will close the issue ;)
