### ISSUE TITLE
Allow for a specific node to be always forced to an array

### ISSUE THREAD

**Issue by LucianPurcarea** [jhuckaby/pixl-xml#20]

**Comment by jhuckaby** [comment]
https://github.com/jhuckaby/pixl-xml#alwaysarray

## alwaysArray

```
ARRAY alwaysArray( MIXED )
```

This function will wrap anything passed to it into an array and return the array, unless the item passed is already an array, in which case it is simply returned verbatim.

```javascript
var arr = XML.alwaysArray( maybe_array );
```
