### ISSUE TITLE
Namespaced elements return an object

### ISSUE THREAD

**Issue by gargantuan** [jhuckaby/pixl-xml#4]
I'm not an XML expert, so I'm not sure if this is the expected behaviour or not - but since it's not documented I thought it worth raising an issue anyway. 

Given the following xml

```
<xml>
    <soap:body>
        <foo>bar</foo>
    <soap:body>
</xml>
```

I can access the value of foo with 

```
let doc = XML.parse(xml)
console.log( doc['soap:body']['foo'] );
// output: bar
```

but if `foo` is namespaced...

```
<xml>
    <soap:body>
        <foo xmlns:myns="http://blah.com/foo">bar</foo>
    <soap:body>
</xml>
```

then I get the following

```
let doc = XML.parse(xml)
console.log( doc['soap:body']['foo'] );
// output: { xmlns:foo "http://bal.com/foo", _Data: "bar"}
```

Which makes it difficult to evaluate the value contained in an element. In my use case, sometimes the elements are name spaced, and sometimes they aren't. I have no control over the XML I receive.

**Comment by 0xff00ff** [comment]
if node have just text contents, it returns string.
if node have attributes, it returns object with "_Data" property, where text contents will be placed, if it exists. Attributes will be as properties.
if node have attributes and subnodes, they both will be as properties, unless you parse xml with parameter "preserveAttributes", otherways all attributes will be stored in "_Attributes" property

maybe it will help.

**Comment by jhuckaby** [comment]
Thanks for the report, @gargantuan, and the additional info @0xff00ff.

Unfortunately, pixl-xml doesn't currently support XML namespaces, at least in the traditional sense, so they just get parsed like any other XML attribute.  @0xff00ff explains this nicely above.  The same thing would happen with any XML attribute, even if it wasn't namespaced, like this:

``` js
var xml_string = '<?xml version="1.0"?><Document>' + 
        '<Node Key="Value">Complex</Node>' + 
        '</Document>';

var doc = XML.parse( xml_string );
console.log( doc );
```

Becomes:

``` js
{
    "Node": {
        "Key": "Value",
        "_Data": "Complex"
    }
}
```

See that `Node` becomes an object in this case, with a `_Data` property containing the raw value.

Please note that the [xml2js](https://www.npmjs.com/package/xml2js) module does the same thing, only with slightly different result objecting properties (definitely the same idea tho):

``` js
var parseString = require('xml2js').parseString;
var raw = '<xml><soap:body><foo xmlns:myns="http://blah.com/foo">bar</foo></soap:body></xml>';
parseString(raw, function (err, result) {
    console.log( JSON.stringify(result, null, "\t") );
});
```

Result:

``` js
{
    "xml": {
        "soap:body": [
            {
                "foo": [
                    {
                        "_": "bar",
                        "$": {
                            "xmlns:myns": "http://blah.com/foo"
                        }
                    }
                ]
            }
        ]
    }
}
```

You mentioned that you sometimes get namespaced XML attributes, and sometimes not.  If you want, you can use a regular expression to strip them all off, just before parsing.  I know this is ugly, but it would probably work for your purposes:

``` js
let doc = XML.parse( xml.replace(/\bxmlns\:\w+\=\"[^\"]*\"/ig, '') );
```

Good luck, and sorry!

\- Joe

**Comment by gargantuan** [comment]
Fair enough - if that's the expected behaviour then I don't need to worry. It's easy enough to ckeck for the existence of a `_Data` property.
