### ISSUE TITLE
Why omit the outmost element?

### ISSUE THREAD

**Issue by MikeyBurkman** [jhuckaby/pixl-xml#5]
I'm really confused why the outermost element is always omitted? Is there a way to get it?

The xml we're parsing will be of different types, and we need to know what that element is in order to route it to the right function. I'd love to move away xml2js (it's slow), but I can't unless I can (easily) get that outermost element.

**Comment by jhuckaby** [comment]
I apologize for the confusion.  Omitting the outermost element was behavior copied from the Perl `XML::Simple` class, on which this is loosely based.  Their thinking was, the XML format only allows for one single outer element, and it's usually something generic like `<Document>` and not typically used or needed in code, so they omit it when parsing.

I will add a property you can set to preserve the outer element.  Please give me 15 minutes, and I'll push a new version ASAP.

**Comment by MikeyBurkman** [comment]
Oh wow. You're amazing!

**Comment by jhuckaby** [comment]
No prob, sir!  My pleasure.  This should do it I think:

Commit: https://github.com/jhuckaby/pixl-xml/commit/bb8e2ac4192c95ec51b87bd7715b1851dbb285ba

Docs:

### preserveDocumentNode

If you want the outermost root node (also called the document node) preserved when parsing, set the `preserveDocumentNode` property to true when parsing.  Example:

``` js
var xml_string = '<?xml version="1.0"?><Document>' + 
    '<Simple>Hello</Simple>' + 
    '<Node Key="Value">Complex</Node>' + 
    '</Document>';

var doc = XML.parse( xml_string, { preserveDocumentNode: true } );
console.log( doc );
```

With the `preserveDocumentNode` flag set to true, this would produce the following object:

``` js
{
    "Document": {
        "Simple": "Hello",
        "Node": {
            "Key": "Value",
            "_Data": "Complex"
        }
    }
}
```

_Also note this bit about composing back to XML:_

If you are composing an XML document which has the document root node preserved (see [preserveDocumentNode](#preserveDocumentNode) above), simply omit the name parameter, and only pass in the object.  Example:

``` js
var xml_string = XML.stringify( doc );
```

**Comment by MikeyBurkman** [comment]
You sir are awesome. Unfortunately I can't give you more praise, but you do get a star.

**Comment by jhuckaby** [comment]
HAHAHAHA!  Thanks man!  I'll take it!
