### ISSUE TITLE
Is there a way to disable indentation?

### ISSUE THREAD

**Issue by adambiggs** [jhuckaby/pixl-xml#9]
An option to disable indentation would be very useful to minimize response sizes when running in production.

**Comment by jhuckaby** [comment]
Hey Adam, this currently isn't available, but I will add this as a feature ASAP.  Great idea, thanks!

**Comment by jhuckaby** [comment]
I have pushed version 1.0.10 with this feature implemented for ya.  You can accomplish it from both the simplified API, and the object-oriented API.  Docs copypasta:

## Compact XML (Simplified API)

To produce compact XML output (i.e. without indentation nor EOLs) you simply have to call `stringify()` with three additional arguments.  Pass in `0` indicating a zero indent level, and then two empty strings, one representing the indentation character (defaults to `\t`) and finally the EOL character (defaults to `\n`).  Example:

``` javascript
var xml_string = XML.stringify( doc, 'Document', 0, "", "" );
console.log( xml_string );
```

This would produce something like:

``` xml
<?xml version="1.0"?><Document><Node Key="Value">Content</Node><Simple>Hello</Simple></Document>
```

If you are composing an XML document which has the document root node preserved (see [preserveDocumentNode](https://github.com/jhuckaby/pixl-xml#preservedocumentnode)), simply pass in an empty string for the name parameter.  Example:

``` js
var xml_string = XML.stringify( doc, "", 0, "", "" );
```

## Custom XML Formatting (Object-Oriented API)

To produce custom XML formatting using the object-oriented API, you can pass two arguments to the `compose()` method.  The first argument represents the indentation character (defaults to `\t`) and the second argument represents the EOL character (defaults to `\n`).

For example, to produce compact XML (i.e. all crammed onto one line) set both arguments to empty strings.  Example:

``` js
console.log( parser.compose("", "") );
```

This would produce the following output:

``` xml
<?xml version="1.0" encoding="UTF-8"?><Document><Node Key="Value">Complex</Node><Simple>Hello, I changed this.</Simple></Document>
```

Hope this helps!

**Comment by adambiggs** [comment]
Awesome! Thanks @jhuckaby 🍻
